# Loading Libraries
library(arules)
library(arulesViz)
library(plyr)
library(dplyr)
library(ggplot2)
library(readxl)

# import dataset
course_list <- list(
  c("Algoritma dan Pemrograman","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","metopen"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","jaringan terdistribusi","matematika diskrit","metopen","komunikasi data"),
  c("struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","manajemen proyek perangkat lunak","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit"),
  c("Pengantar Informasi","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","pemrograman web","metopen"),
  c("Algoritma dan Pemrograman","pemrograman 1","teknik digital","struktur data","sistem operasi","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","sistem keamanan","pembelajaran berbasis multimedia","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek"),
  c("Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen"),
  c("Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","struktur data","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web"),
  c("Algoritma dan Pemrograman","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","pengembangan sistem berorientasi objek","pemrograman web","metopen"),
  c("pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","teknik digital","struktur data","sistem operasi","basis data","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen"),
  c("pemrograman 1","teknik digital","struktur data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","pengembangan sistem berorientasi objek","pemrograman web","metopen"),
  c("Perakitan dan Instalasi Komputer","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek"),
  c("Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","jaringan terdistribusi","matematika diskrit"),
  c("Pengantar Informasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen"),
  c("Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pemrograman web","metopen","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","struktur data","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","praktik pengembangan apk mobile","manajemen sistem informasi","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pengembangan sistem berorientasi objek","pemrograman web","metopen","komunikasi data"),
  c("Algoritma dan Pemrograman","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","sistem keamanan","pembelajaran berbasis multimedia","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","manajemen sistem informasi","komunikasi data"),
  c("Pengantar Informasi","Algoritma dan Pemrograman","Perakitan dan Instalasi Komputer","pemrograman 1","teknik digital","struktur data","sistem operasi","basis data","interaksi manusia dan komputer","komunikasi data","pemrograman 2","praktik jaringan komputer","pemrograman visual 1","media digital","desain komunikasi visual","mobile & cloud computing architecture","stategi pembelajaran visual","pengolahan citra digital","komunikasi nirkabel","manajemen proyek perangkat lunak","praktik pengembangan apk mobile","administrasi jaringan","multimedia interaktif","jaringan terdistribusi","matematika diskrit","pemrograman web","metopen")
)

## Set transaction names
names(course_list) <- paste("ID",c(1:33), sep = "")
course_list

## Use the constructor to create transactions
course <- transactions(course_list)
course
itemFrequencyPlot(course, support=0.05)

rules <- apriori(course, supp = 0.5, conf = 0.9, target = "rules")
inspect(rules[8:40])

writexl::write_xlsx(data.frame(table(rules@quality$support)),"Support.xlsx")
writexl::write_xlsx(data.frame(table(rules@quality$confidence)),"Confidence.xlsx")

Sup_and_Conf<-data.frame(Support = rules@quality$support,
                         Confidence = rules@quality$confidence)
writexl::write_xlsx(data.frame(with(Sup_and_Conf,
     +      table(Support, Confidence, useNA = "ifany"))),"Support vs Confidence.xlsx") # Table Conf VS Support

## Visualizing the association rules
top.conf <- sort(rules, decreasing = TRUE, na.last = NA, by = "confidence")
plot(top.conf[1:20], method="graph")

top.lift <- sort(rules, decreasing = TRUE, na.last = NA, by = "lift")
plot(top.lift[1:20], method="graph")

